### ISSUE TITLE
感谢大神，但是编译通不过哈

### ISSUE THREAD

**Issue by eric7166** [zhuyongqing/LiveTriviaHook#1]
<img width="270" alt="qq20180125-133721 2x" src="https://user-images.githubusercontent.com/4892119/35372423-e3e0a710-01d4-11e8-8ff3-ee267e3b2f87.png">

**Comment by zhuyongqing** [comment]
theos 和 monkeyApp的环境 都装好了吗

**Comment by zhuyongqing** [comment]
最好不要直接编译我的项目,你按照教程把逆向一些的环境都配置好,然后自己创建一个新MonkeyApp项目,直接编译一下试试,如果通过了，再把我项目里的一些重要代码复制过去，避免环境目录不同出错。
