### ISSUE TITLE
一进答题页面就crash

### ISSUE THREAD

**Issue by EdwardBX** [zhuyongqing/LiveTriviaHook#2]
crash 在 UIButton *option1 = questionView.subviews[5].subviews[0]; 
提示 subviews 只有5个，数组越界。。。
是不是 APP 改版了？
版本 V1.0.7.

**Comment by zhuyongqing** [comment]
是的，我这个是1.0.4的，不过应该还有其它方法的,大家可以一起找找，等我找到新的方法会更新项目。

**Comment by zhuyongqing** [comment]
已修复1.0.7页面层级的问题。
